Database:
  Connection:
    host: 127.0.0.1
    username: wowdb
    password: wowdb
    sqlalchemy_connection_string: "mysql+pymysql://{user}:{password}@{host}/{db_name}?charset=utf8mb4"

  DBNames:
    login_db: wowdb_login
    world_db: wowdb_world
    realm_db: wowdb_realm

WebsocketServer:
  Connection:
    # if located on vps or any another external server, you should set external ip instead of localhost
    host: 127.0.0.1
    port: 9001

RedisServer:
  Connection:
    host: 127.0.0.1
    port: 6379

Realm:
  Connection:
    LoginServer:
      host: 0.0.0.0
      port: 3724

    WorldServer:
      # if located on vps or any another external server, you should set external ip instead of localhost
      host: 127.0.0.1
      port: 8085
      realm_name: Idewave-core

  Settings:
    min_timeout: 0.01

  General:
    # Message of the day ('@' for the newline)
    motd: Welcome to the idewave-core server

World:
  Gameplay:
    game_speed: 0.01666667
    # be careful when edit this option cause the smaller it is the more memory usage by octrees
    update_dist: 200

  Weather:
    change_weather_timeout: 300
    instant_change: False
    # percentage
    Chances:
      fine: 100
      rain: 50
      snow: 50
      storm: 10
      thunders: 30
      blackrain: 0

  Chat:
    ChatRange:
      say_range: 25
      yell_range: 300

  Object:
    Defaults:
      scale_x: 1.0

    Unit:
      Defaults:
        base_min_damage: 1.0
        base_max_damage: 2.0
        base_attack_time: 2000
        bounding_radius: 0.388999998569489
        combat_reach: 1.5
        base_block: 5.0
        base_parry: 5.0

      Player:
        Defaults:
          min_level: 1
          max_level: 70
          # copper
          start_money: 10000

          Movement:
            speed_walk: 2.5
            speed_run: 7.0
            speed_run_back: 4.5
            speed_swim: 4.722222
            speed_swim_back: 2.5
            speed_flight: 7.0
            speed_flight_back: 4.5
            speed_turn: 3.141594
